export const SUBMIT_FORM_PRODUCT = "SUBMIT_FORM_PRODUCT";
export const PRODUCT_SAVED = "PRODUCT_SAVED";
export const PRODUCT_SAVED_ERROR = "PRODUCT_SAVED_ERROR";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";